project:
  type: book
  output-dir: docs
  
book:
  title: "Mathematical Methods for Biology, Part 2"
  author: "Dmitry Kondrashov"
  #date: "9/11/2022"
  chapters:
    - index.qmd
    - PCA.qmd
    - gradient_optimization.qmd
    - fourier_convolution.qmd
    - optimization_MC.qmd
    - markov_chains.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false   
  pdf:
    documentclass: scrreprt
pdf-engine: pdflatex
latex-auto-install: true
jupyter: python3
