---
title: "COVID data reader"
author: "Dmitry Kondrashov"
date: "1/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
#covid_tb <- read_csv("time_series_covid19_confirmed_global.csv")
covid_us <- read_csv("time_series_covid19_confirmed_US.csv")
```
## Data source

Data was downloaded from https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series on January 21, 2021.

```{r}
covid_italy <- covid_tb %>% filter(`Country/Region` == 'Italy')
italy_tidy <- covid_italy %>% pivot_longer(
     cols = !c(`Province/State`, `Country/Region`, Long, Lat), 
     names_to = "date", 
     values_to = "cases")
italy_short <- italy_tidy %>% select(`Country/Region`, date, cases) %>%  filter (mdy(date) %in% seq(ymd('2020-02-01'),ymd('2020-03-29'), by = 'days')) 
```

```{r}
italy_short %>% ggplot() + aes(x = mdy(date), y = cases) + geom_point()
```
```{r}
write_csv(italy_short, "Italy_COVID.csv")
```

